P3 ADDED Felix the Cat.
(base) PS C:\PyFiles\CSIS-44671\streaming-02-multiple-processes> & C:/Users/lejones/AppData/Local/Programs/Python/Python310/python.exe c:/PyFiles/CSIS-44671/streaming-02-multiple-processes/multiple_processes.py


STARTING UP.............................
It's 2023-01-24 at 10:25 PM

This file is running on:    nt Windows 10
The Python version is:      3.10.9
 
The Python interpreter is at: 
 C:\Users\lejones\AppData\Local\Programs\Python\Python310\python.exe


DELETED tabble pets.
CREATED table pets.

P1 getting ready to insert Ace the Dog.
P1 ADDED Ace the Dog.
P2 getting ready to insert Cooper the Rabbit.
P3 getting ready to insert Emma the Rabbit.
P1 getting ready to insert Buddy the Dog.
P1 ADDED Buddy the Dog.
Process Process-2:
Traceback (most recent call last):
  File "C:\Users\lejones\AppData\Local\Programs\Python\Python310\lib\multiprocessing\process.py", line 314, in _bootstrap
    self.run()
  File "C:\Users\lejones\AppData\Local\Programs\Python\Python310\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "c:\PyFiles\CSIS-44671\streaming-02-multiple-processes\multiple_processes.py", line 106, in process_two
    insert_pet("P2", "Cooper", "Rabbit")
  File "c:\PyFiles\CSIS-44671\streaming-02-multiple-processes\multiple_processes.py", line 95, in insert_pet
    cur.execute(sql)
sqlite3.OperationalError: database is locked
Process Process-3:
Traceback (most recent call last):
  File "C:\Users\lejones\AppData\Local\Programs\Python\Python310\lib\multiprocessing\process.py", line 314, in _bootstrap
    self.run()
  File "C:\Users\lejones\AppData\Local\Programs\Python\Python310\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "c:\PyFiles\CSIS-44671\streaming-02-multiple-processes\multiple_processes.py", line 110, in process_three
    insert_pet("P3","Emma", "Rabbit")
  File "c:\PyFiles\CSIS-44671\streaming-02-multiple-processes\multiple_processes.py", line 95, in insert_pet
    cur.execute(sql)
sqlite3.OperationalError: database is locked
(base) PS C:\PyFiles\CSIS-44671\streaming-02-multiple-processes> 

